`include "parameter.v"

module tf_ROM_radix4 (
    input clk,
    input [7:0] A,
    input REN,
    output reg [(12*4)-1:0] Q
);
    // Generated by gen_tf_rom_radix4.py
    reg [(12*4)-1:0] rom [0:84];
    initial $readmemh("tf_rom_radix4.mem", rom);

    always @(posedge clk) begin
        if (REN) Q <= rom[A];
        else Q <= 'b0;
    end
endmodule
