# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.runs/synth_1/polytop_RE.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu15eg-ffvb1156-3-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.cache/wt [current_project]
set_property parent.project_path D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/VivadoProject/Multlane_RENTT/Multlane_RENTT.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/parameter.v
set_property file_type "Verilog Header" [get_files D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/parameter.v]
read_verilog -library xil_defaultlib {
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/basic_unit/bitmod_wocsa3/CSA1.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/basic_unit/bitmod_wocsa3/CSA2.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/basic_unit/Div2.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/basic_unit/bitmod_wocsa3/Hybrid_compress_wocsa3.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/basic_unit/MA.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/basic_unit/MS.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/basic_unit/Modmul.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/RBFU.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/addr_gen.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/arbiter.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/auxiliary.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/bank.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/basic_unit/bitmod_wocsa3/bitmod_wocsa3.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/fsm.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/basic_unit/intmul.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/memory_map.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/network_RBFU_in.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/network_RBFU_out.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/network_bank_in.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/tf_ROM.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/tf_address_generator.v
  D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/sources_1/RTL/polytop_RE.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/constrs_1/new/NTT.xdc
set_property used_in_implementation false [get_files D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/constrs_1/new/NTT.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/VivadoProject/Multlane_RENTT/Multlane_RENTT.srcs/utils_1/imports/synth_1/polytop.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top polytop_RE -part xczu15eg-ffvb1156-3-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef polytop_RE.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file polytop_RE_utilization_synth.rpt -pb polytop_RE_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
